language: clojure
before_install:
  - sudo apt-get install libpcap-dev -qq
  - lein2 bootstrap
script:
  - sudo LEIN_ROOT=1 lein2 do javac, test
lein: lein2
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
