language: clojure
before_install:
  - sudo apt-get install libpcap-dev -qq
script:
  - sudo LEIN_ROOT=1 lein2 do javac, test
after_script:
  - sudo LEIN_ROOT=1 lein2 cloverage -o cov --coveralls && curl -F 'json_file=@cov/coveralls.json' 'https://coveralls.io/api/v1/jobs'
lein: lein2
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8
