version: 2
jobs:
  build:
    working_directory: ~/clj-net-pcap
    machine: true
    environment:
      LEIN_ROOT=nbd
    steps:
      - checkout
      - restore_cache:
          key: << checksum "project.clj" >>
      - run: apt-get update; apt-get install libpcap0.8 -qq
      - run: ln -s /usr/lib/x86_64-linux-gnu/libpcap.so.0.8 /usr/lib/x86_64-linux-gnu/libpcap.so
      - run: .circleci/bin/lein deps
      - save_cache:
          paths:
            - $HOME/.m2
            - $HOME/.lein
          key: << checksum "project.clj" >>
      - run: .circleci/bin/lein do test, uberjar
      - store_artifacts:
          path: target/uberjar/clj-net-pcap.jar
destination: uberjar
